# SPDX-License-Identifier: GPL-2.0-or-later
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "liblore"
version = "0.9-dev"
description = "Shared library for public-inbox / lore.kernel.org access"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-2.0-or-later"
license-files = ["LICENSES/*.txt"]
authors = [
    { name = "Konstantin Ryabitsev", email = "konstantin@linuxfoundation.org" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Communications :: Email",
    "Topic :: Communications :: Email :: Mailing List Servers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "requests>=2.31",
]

[project.optional-dependencies]
auth = ["authheaders>=0.15"]

[project.urls]
Homepage = "https://git.kernel.org/pub/scm/utils/liblore/liblore.git"
Repository = "https://git.kernel.org/pub/scm/utils/liblore/liblore.git"

[dependency-groups]
dev = [
    "authheaders>=0.15",
    "build",
    "mypy",
    "pyright",
    "pytest",
    "pytest-asyncio",
    "responses",
    "ruff",
    "ty",
    "types-requests",
    "typing-extensions",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--tb=short"
asyncio_default_fixture_loop_scope = "function"

[tool.mypy]
strict = true

[tool.pyright]
# pyright automatically ignores virtual environments and other directories, but
# once we specify `exclude`, we're on our own. The matrix in ci-matrix.sh
# creates .venv-<version> environments, so match them all. See
# https://github.com/microsoft/pyright/issues/9057#issuecomment-2366938099.
exclude = [".venv*"]
typeCheckingMode = "strict"

executionEnvironments = [
    # We're testing private APIs quite a bit.
    { root = "tests", reportPrivateUsage = false },
]

[tool.ty.rules]
all = "error"

[tool.ruff.lint]
extend-select = ["ARG", "I"]

[tool.ruff.format]
quote-style = "single"
